factory: LPAENetParam
num_users: 630
embd_dim: 128
com_memory: true
num_sab: 2
num_points: 0
num_seeds: 1
num_proto: 64
num_heads: 4
backbone: resnet34
use_semantic: false
use_visual: true
use_nn_feature: true
logdet: true
loss_weight: { rank_loss: 1.0, l1reg: 1.0e-2, l2reg: 1.0e-4 }
